version: '3'
services:
   #  backend:
   #     image: sergeythehuman/whereismymoney:v1.3
   #     container_name: whereIsMyMoneyBackend
   #     networks:
   #        - WhereIsMyMoney
   #     ports:
   #        - '3000:3000'
   #     restart: always
   postgresql:
      image: postgres
      container_name: whereIsMyMoneyDB
      networks:
         - WhereIsMyMoney
      ports:
         - '5435:5432'
      storage_opt:
         size: '1G'
      environment:
         - POSTGRES_HOST=localhost
         - POSTGRES_USER=SergeyTheHuman
         - POSTGRES_PASSWORD=42531682
         - POSTGRES_DB=whereIsMyMoneyDB
      command: postgres
      restart: always
   redis:
      image: redis:alpine3.14
      container_name: whereIsMyMoneyRedis
      networks:
         - WhereIsMyMoney
      ports:
         - '6379:6379'
      restart: always

networks:
   WhereIsMyMoney:
      name: WhereIsMyMoney
      external: true
