version: '3'
services:
   postgresql:
      image: postgres
      container_name: whereIsMyMoneyDB
      networks:
         - WhereIsMyMoney
      ports:
         - '5435:5432'
      environment:
         - POSTGRES_HOST=localhost
         - POSTGRES_USER=SergeyTheHuman
         - POSTGRES_PASSWORD=42531682
         - POSTGRES_DB=whereIsMyMoneyDB
      command: postgres
      restart: always
   redis:
      image: redis:alpine3.14
      container_name: whereIsMyMoneyRedis
      networks:
         - WhereIsMyMoney
      ports:
         - '6379:6379'

networks:
   WhereIsMyMoney:
      name: WhereIsMyMoney
      external: true
